name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: https://github.com/gbrGabriel/templates/tree/master/profile-summary-card-output/dracula@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY-CARDS-TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
